# Generated by Django 3.1.2 on 2021-10-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211001_0049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_description',
        ),
    ]
