# Generated by Django 3.1.2 on 2021-10-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211001_0847'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_details',
        ),
    ]
