# Generated by Django 3.1.2 on 2021-10-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='category',
            new_name='cart_category',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='description',
            new_name='cart_description',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='cart_name',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='cart_price',
        ),
    ]
